package classes.Enums;

/**
 * Created by USER on 13-Jan-17.
 */
public enum IntendedUseVehicle {
    SOCIAL_AND_DOMESTIC,
    MOTOR_RACING_TRAILS_AND_RALLIES,
    CARRIAGE_OWN_GOODS,
    HIRE_OR_REWARD,
    EMPLOYEES,
    LEARN_TO_DRIVE,
    CONNECTION_WITH_BUSINESS,
    EMPLOYERS_BUSINESS,
    FLAMMABLE_EXPLOSIVE_SUBSTANCES,
    EMERGENCY_SERVICE
}
